FROM node:16.15

WORKDIR /app

COPY package*.json ./api/

ARG NODE_ENV
RUN if [ "$NODE_ENV" = "dev" ]; \
        then cd api && npm install; \
        else cd api && npm install --only=production; \
        fi

COPY . ./api/
CMD [ "cd", "api", "&&", "npm", "run", "dev" ]